name: "Build"

on:
  workflow_dispatch:
  push:
  release:
    types:
      - "published"

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - "windows-2022"
          - "ubuntu-22.04"
          - "macos-12"
        python:
          - "3.11.0"
        cx-freeze:
          - "v6.11.1"  # Later versions have bugs on macOS - also Windows ignores this since it needs newer versions for Python 3.11+
    name: "${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"
    if: "github.event_name != 'push' || contains(github.event.head_commit.message, '+ BUILD')"
    steps:

      # === SETUP ===

      - name: "Set git to use lf"
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: "Setup Python"
        uses: "actions/setup-python@v4"
        with:
          python-version: "${{ matrix.python }}"

      - name: "Setup MacPorts (macOS)"
        if: "runner.os == 'macOS'"
        run: |
          wget https://github.com/macports/macports-base/releases/download/v2.8.0/MacPorts-2.8.0-12-Monterey.pkg
          sudo installer -pkg ./MacPorts-2.8.0-12-Monterey.pkg -target /
          rm ./MacPorts-2.8.0-12-Monterey.pkg
          echo "/opt/local/bin:/opt/local/sbin" >> $GITHUB_PATH

      - name: "Setup GTK (Linux)"
        if: "runner.os == 'Linux'"
        run: |
          sudo apt install libgirepository1.0-dev libwebkit2gtk-4.1-0

      - name: "Setup GTK (macOS)"
        if: "runner.os == 'macOS'"
        run: |
          sudo port install gobject-introspection -universal
          sudo port install gtk3 -universal -x11 +quartz
          sudo port install webkit2-gtk -debug -minibrowser -x11 +quartz

      - name: "Setup cx_Freeze (Windows)"
        if: "runner.os == 'Windows'"
        run: |
          python -m pip install --pre -f https://lief.s3-website.fr-par.scw.cloud/latest/lief/ lief
          python -m pip install --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Logging
          python -m pip install --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze

      - name: "Setup cx_Freeze (Linux, macOS)"
        if: "runner.os != 'Windows'"
        run: |
          python -m pip install -U 'git+https://github.com/marcelotduarte/cx_Freeze.git@${{ matrix.cx-freeze }}'

      # === BUILD ===

      - name: "Clone repo"
        uses: "actions/checkout@v3"
        with:
          path: "."

      - name: "Install requirements"
        run: |
          python -m pip install -U 'numpy' 'cython>=3.0a11'
          python -m pip install 'https://download.lfd.uci.edu/pythonlibs/archived/lxml-4.9.0-cp311-cp311-win_amd64.whl' || true
          python -m pip install -U -r ./requirements.txt
        # numpy is installed before to avoid the numpy formathandler warning on startup with pyopengl-accelerate
        # cython version restriction is to fix complciation of opengl-accelerate on python 3.11+
        # lxml is installed from a direct wheel on windows because there are no official binaries for python 3.11+ yet

      - name: "Mark as release"
        if: "github.event_name == 'release'"
        run: |
          sed "s/is_release = False/is_release = True/g" ./main.py > ./main.py.new
          rm ./main.py
          mv ./main.py.new ./main.py

      - name: "Mark build number"
        if: "github.event_name != 'release'"
        run: |
          sed "s/build_number = 0/build_number = ${{ github.run_number }}/g" ./main.py > ./main.py.new
          rm ./main.py
          mv ./main.py.new ./main.py

      - name: "Build (Windows, Linux)"
        if: "runner.os != 'macOS'"
        run: |
          python ./setup.py build
          mv ./build/exe.*/ ./dist/

      - name: "Build (macOS)"
        if: "runner.os == 'macOS'"
        run: |
          python ./setup.py bdist_mac
          mkdir ./dist/
          mv ./build/*.app/ ./dist/

      - name: "Resolve symlinks (Linux, macOS)"
        if: "runner.os != 'Windows'"
        run: |
          cd ./dist/
          find ./ -type l -exec echo Resolving {} \; -exec sed -i '' {} \;

      - name: "Import codesign certificate (macOS)"
        if: "runner.os == 'macOS'"
        uses: "apple-actions/import-codesign-certs@v1"
        with:
          p12-file-base64: "${{ secrets.CODESIGN_P12_BASE64 }}"
          p12-password: "${{ secrets.CODESIGN_P12_PASSWORD }}"

      - name: "Codesign (macOS)"
        if: "runner.os == 'macOS'"
        run: |
          cd ./dist/
          find ./ -type f -empty -delete
          codesign -s "${{ secrets.CODESIGN_P12_NAME }}" --deep ./*.app

      # === ARTIFACT ===

      - name: "Zip artifact"
        run: |
          cd ./dist/
          7z a ../${{ github.event.repository.name }}-${{ runner.os }}.zip .

      - name: "Upload commit artifact"
        if: "github.event_name != 'release'"
        uses: "actions/upload-artifact@v3"
        with:
          name: "${{ runner.os }}"
          path: "./${{ github.event.repository.name }}-${{ runner.os }}.zip"

      - name: "Upload release artifact"
        if: "github.event_name == 'release'"
        uses: "softprops/action-gh-release@v1"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          files: "./${{ github.event.repository.name }}-${{ runner.os }}.zip"

  source:
    name: "source"
    runs-on: "ubuntu-latest"
    if: "github.event_name != 'push' || contains(github.event.head_commit.message, '+ BUILD')"
    steps:

      # === SETUP ===

      - name: "Set git to use lf"
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      # === PACKAGE ===

      - name: "Clone repo"
        uses: "actions/checkout@v3"
        with:
          path: "."

      - name: "Mark as release"
        if: "github.event_name == 'release'"
        run: |
          sed "s/is_release = False/is_release = True/g" ./main.py > ./main.py.new
          rm ./main.py
          mv ./main.py.new ./main.py

      - name: "Mark build number"
        if: "github.event_name != 'release'"
        run: |
          sed "s/build_number = 0/build_number = ${{ github.run_number }}/g" ./main.py > ./main.py.new
          rm ./main.py
          mv ./main.py.new ./main.py

      - name: "Package"
        run: |
          mkdir ./dist/
          cp -r ./modules/         ./dist/
          cp -r ./resources/       ./dist/
          cp    ./LICENSE          ./dist/
          cp    ./main.py          ./dist/
          cp    ./requirements.txt ./dist/

      # === ARTIFACT ===

      - name: "Zip artifact"
        run: |
          cd ./dist/
          7z a ../${{ github.event.repository.name }}-Source.zip .

      - name: "Upload commit artifact"
        if: "github.event_name != 'release'"
        uses: "actions/upload-artifact@v3"
        with:
          name: "Source"
          path: "./${{ github.event.repository.name }}-Source.zip"

      - name: "Upload release artifact"
        if: "github.event_name == 'release'"
        uses: "softprops/action-gh-release@v1"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          files: "./${{ github.event.repository.name }}-Source.zip"

  release:
    name: "release"
    runs-on: "ubuntu-latest"
    if: "github.event_name == 'release'"
    needs:
      - build
      - source
    steps:

      - name: "Set git to use lf"
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: "Clone repo"
        uses: "actions/checkout@v3"
        with:
          path: "."

      - name: "Update release"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          python ./.github/workflow_data/release.py

      - name: "Delete skipped workflow runs"
        if: "github.event_name == 'release'"
        uses: "Willy-JL/delete-skipped-workflow-runs@main"
        with:
          retain_days: 0
          keep_minimum_runs: 0
